server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - HostHeader=car-service
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - HostHeader=bike-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - HostHeader=user-service

