server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/jerrytocto/microservice-three
          search-paths: config-data
  application:
    name: config-server
